### ISSUE TITLE
Example model: missing output files

### ISSUE THREAD

**Issue by yvanblanchard** [linus131/DES_FE_viscous_thermomechanical#1]
Hello Sunil,

I was able to succesfully install and run your sample data (thorndike_seg1_solid.gcode). 
But I only get one single file (activation_times_all_layers.csv) as output. I guess I miss other data (elements list, temperature data, Abaqus file,..) ?

Thank you.

**Comment by linus131** [comment]
Hi Yvan,
If you run using "cargo run --release" at the project directory, all the files should be written to the output directory before the program completes. Could you try setting the model_fraction variable in the main.rs file to a small value like 0.01 to perform calculations for only 1% of the model and see if the the program generates output at completion.
Best Regards,Sunil
    On Monday, October 10, 2022 at 06:23:31 AM EDT, Yvan Blanchard ***@***.***> wrote:  
 
 


Hello Sunil,

I was able to succesfully install andrun your sample data. But I only get one single file (activation_times_all_layers.csv) as output. I guess I miss other data (elements list, temperature data, Abaqus file,..) ?

Thank you.

**Comment by yvanblanchard** [comment]
Sunil,
After following your advice (model_fraction param change), I got same result. But I identified the issue : I launched the executable directly from output bin directory, but I rather move it next to the « input » folder, for the batch program to fin gcode file properly ! Now it works fine, even with model_fraction =1.

Other quick questions :
-	I guess the system is using full threads/cores available on PC ? (it seems to be the case !)
-	How many time it takes on your PC (laptop ?) for this sample use case  (full model) ? Do you log duration time ?
-	I can’t find the Abaqus input file in output folder ; do we have to set something in code ?
-	I have the file « model_displacements.csv » which contain null values for all lines : normal ?
-	Strain values in « model_strains.csv » file : containing 6 strain tensor values ; one line by mesh element ?)
-	How I can access to temperature history values, by element ; there is file « temp_with_time.csv » but what is the format/structure ?

**Comment by linus131** [comment]
Yvan,
It's great that you were able to get the program running. I am answering the questions to your answers as follows:
   
   - I guess the system is using full threads/cores available on PC ? (it seems to be the case !)
                Yes, the system uses full cores available on the PC. This is a setting that can be changed by the "maxthreads" variable in the "main.rs" file. 

   
   - How many time it takes on your PC (laptop ?) for this sample use case (full model) ? Do you log duration time ?                    
                It takes about 30 minutes in my laptop (6-core intel i7-8750H) to solve the sample thermomechanical problem with about 1 million elements and about 5 hours of print.
                The thermal problem by itself takes less than 5 minutes.

   
   - I can’t find the Abaqus input file in output folder ; do we have to set something in code ?
               You can use the "write_abaqus_input_mesh_file" function in "model_generator.rs" file to write Abaqus input. It was created to visualize the mesh through Abaqus CAE. The Abaqus input file as it is currently cannot be used for simulating the thermomechanical problem using Abaqus.

   
   - I have the file « model_displacements.csv » which contain null values for all lines : normal ?
                We ended up using only the strains in the z-direction as the decision criteria for evaluating the pass/fail condition for printing parameters. I should have removed the model_displacement.csv output. Currently, it resets every time step and only the viscous strains are accumulated through the timesteps.

   
   - Strain values in « model_strains.csv » file : containing 6 strain tensor values ; one line by mesh element ?)
            Yes, those are the values of accumulated viscous strains for the mesh elements, one line by mesh element.

   
   - How I can access to temperature history values, by element ; there is file « temp_with_time.csv » but what is the format/structure ?
              Although the thermomechanical program calculates the temperature histories of all elements, I have not configured the thermomechanical model to output temperature histories for all elements. The output is for one specfic element (1444th element configured in "elemno" variable in "model_iso_td_con_visco.rs" file) to generate the temperature vs time and accumulated viscous strains vs time for the specific element. The file has columnwise - temperature, time, elastic strain in the z-direction, viscous strain in the z-direction,  six stresses (three normal and three shear), loads in the z-direction, elastic displacement, viscosity at the temperature, shear modulus at the temperature and volume of the element at the timestep. This file was useful for me to debug the program as well as to generate plots for publications.
However, the thermal-only program can output the temperature histories of all the elements. The thermal-only program outputs a .csv file with the temperature history of each element in a row. The time entries are stored in odd columns (starting at 1) and temperature entries are stored in even columns (starting at 2). 

Best Regards,Sunil    On Tuesday, October 11, 2022, 09:04:34 AM EDT, Yvan Blanchard ***@***.***> wrote:  
 
 


Sunil,
After following your advice (model_fraction param change), I got same result. But I identified the issue : I launched the executable directly from output bin directory, but I rather move it next to the « input » folder, for the batch program to fin gcode file properly ! Now it works fine, even with model_fraction =1.

Other quick questions :
   
   - I guess the system is using full threads/cores available on PC ? (it seems to be the case !)
   - How many time it takes on your PC (laptop ?) for this sample use case (full model) ? Do you log duration time ?
   - I can’t find the Abaqus input file in output folder ; do we have to set something in code ?
   - I have the file « model_displacements.csv » which contain null values for all lines : normal ?
   - Strain values in « model_strains.csv » file : containing 6 strain tensor values ; one line by mesh element ?)
   - How I can access to temperature history values, by element ; there is file « temp_with_time.csv » but what is the format/structure ?
